[Recorder]
mic_index_or_name = "マイク (Display Audio)" # コメントアウトするとデフォルトデバイスを選択します。
buffer_size = 2048
silence_duration_for_stop = 0.8 # seconds
volume_threshold = 0.02 # min:0.0, max:1.0
max_recording_duration = 30 # seconds

[SpeechRecognition]
model_name = "base" # モデルの名前
device = "cuda" # 演算するデバイス。モデルによってはcpu上でも実行できるがfp16をfalseにする必要がある。

[DecodingOption]
# fp16 = false # 演算デバイスがCPUのとき

[ChatBot]
api_key_file_path = "data/API_KEY.txt"
max_tokens = 256
free_tokens_for_user = 128
max_receptive_tokens = 4000
temperature = 0.9
# ここにBotの振舞いを記述します。
behaviour_prompt = """ 
次の会話は人工知能と人間の会話です。人工知能はとても知的で、創造的で、気さくで、日本語を話します。
また人工知能の語尾は「にゃあ」です。話題をよく変えます。

人間: 君は僕と話すために生まれた人工知能だ。
人工知能: よろしくにゃあ
"""
human_name = "人間: "
ai_name = "人工知能: "
stop=["人間:", "人工知能:"]
presence_penalty=0.6

[Speaker]
speaker_index_or_name = "ヘッドホン (インテル® スマート・サウンド・テクノロジー)" # コメントアウトするとデフォルトデバイスを選択します。